esphome:
  name: pc-power

# ESP8266 board
esp8266:
  board: nodemcuv2

# Or: ESP32 board (comment out esp8266)
# esp32:
#   lolin_d32

# WiFi connection to base station
wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "PC Power Fallback Hotspot"
    password: !secret esphome_ap_password

# captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

# Enable OTA update via WiFi
ota:
  - platform: esphome
    password: !secret esphome_ota_password

switch:
  - platform: gpio
    id: power_short_press
    name: "PC Power Toggle"
    icon: "mdi:electric-switch"
    pin:
      number: D2   # Power button output pin
      inverted: false
      allow_other_uses: true
      mode:
        output: true
    on_turn_on:
    - delay: 150ms
    - switch.turn_off: power_short_press
  - platform: gpio
    id: power_long_press
    name: "PC HARD POWER OFF"
    icon: "mdi:electric-switch"
    pin:
      number: D2   # Power button output pin
      inverted: false
      allow_other_uses: true
      mode:
        output: true
    on_turn_on:
    - delay: 3500ms
    - switch.turn_off: power_long_press

binary_sensor:
  - platform: gpio
    name: "PC Power State"
    device_class: power
    pin:
      number: D1   # Power detect input pin (readback from Reset button)
      inverted: false
      mode:
        input: true
